### ISSUE TITLE
Copying operations in different labs should not override clipboard items

### ISSUE THREAD

**Issue by junkiattan** [PowerPointLabs/PowerPointLabs#1597]
For each of the different labs, some of the labs replaces the clipboard image. Would be good to use the ClipboardUtil method that prevents the clipboard from being overridden.
1. Sync Lab
- [x] Copy #1597

2. Effects Lab

- [ ] Magnifying glass
- [x] Create Spotlight #1597
- [x] Blur Selected #1597
- [x] Blur Remainder #1597
- [x] Blur all except selected #1597
- [x] Recolor remainder #1597
- [x] Recolor all except selected #1597

3. Shortcuts Lab

- [x] Convert to picture #1580
- [x] Add to shapes lab #1636 

4. Paste Lab

- [x] Paste into group #1634 

5. Agenda Lab

- [x] Create Text Agenda #1597
- [x] Create Visual Agenda #1597
- [x] Create Sidebar Agenda #1597
- [x] Sync agenda #1597

6. Zoom Lab

- [x] Drill down #1597
- [x] Step back #1597
- [x] Zoom to area #1597

**Comment by leeyh20** [comment]
related to #1353

**Comment by leeyh20** [comment]
Could we separate this into child issues? This could be the parent issue.

**Comment by iskandarzulkarnaien** [comment]
Have tested the following for Effects Lab on Office 365:

- [X] Magnifying glass (Seems to be no issue, clipboard is preserved)
- [ ] Create Spotlight (Clipboard overridden)
- [ ] Blur Selected (Clipboard overridden by selected shape)
- [ ] Blur Remainder (Clipboard overridden by selected shape)
- [ ] Blur all except selected (Clipboard overridden by selected shape)
- [ ] Recolor remainder (Clipboard overridden by selected shape)
- [ ] Recolor all except selected (Clipboard overridden by selected shape)
