### ISSUE TITLE
New Lab: Tooltips Lab

### ISSUE THREAD

**Issue by ChesterSng** [PowerPointLabs/PowerPointLabs#1767]
Tooltips Labs will help users add Tooltips to shapes and text by using Trigger Animations.
- [x] Implement the button and the dropdown menu on the Ribbon.
- [x] Implement Create Tooltip (Add tooltip to a shape)
- [x] Implement Create Tooltip (Add tooltip and a shape [trigger])
- [x] ~Implement settings whereby normal animations (onclick) can be used to display tooltip~

**Phase 1**
- [x] Create call out shape and trigger shape (If there is a selection, add call out shape to selection. If no selection create call out shape and trigger shape)
- [x] Link trigger animation to another shape
- [x] Create animation of callout
- [x] Create auto text sizing textbox on top of shape (only for callout shape for now)
- [x] Integrate changes

**Phase 2** 
- [x] Settings (Henry)
  - [x] Choice of animation
  - [x] Choice of default shape
  - [x] ~Choice of exiting on second click~
- [x] ~Placeholder text in textbox~ (Henry)
- [x] Add exit animation so callout disappears on second click (Chester)
- [x] Change to `Create Tooltip`, `Create Callout`, `Create Trigger` (Bryan)
- [x] Change behaviour of `Assign Tooltip` on second assignment to the same trigger to have callout shapes appear together (Chester)

**Issues**
- [x] Create Tooltip button does not respond when text is selected (inside a textbox)
- [x] When a loop is created, no shapes will appear in slideshow (do we want to address this?)

**Comment by damithc** [comment]
`ToolTip` or `Tooltip`?

**Comment by ChesterSng** [comment]
Oops yes **Tooltip** :P

**Comment by YuPeiHenry** [comment]
@ChesterSng It seems that there might be some problem with default text on PPT2010: https://social.msdn.microsoft.com/Forums/office/en-US/e7e11675-9f5d-4657-90ab-c6b278097576/powerpoint-slide-titles-how-to-set-manually-programatically?forum=officegeneral

**Comment by ChesterSng** [comment]
Is this w.r.t the placeholder text in textboxes to be placed in the callouts? @YuPeiHenry

**Comment by YuPeiHenry** [comment]
> Is this w.r.t the placeholder text in textboxes to be placed in the callouts? @YuPeiHenry

Yes. I'm looking into using listeners to do the placeholder text.

**Comment by ChesterSng** [comment]
Closing this issue since `tooltips-lab` branch has been merged into `dev-release`
